name: Publish to HuggingFace

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          version: latest

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv tool install hf
      - name: Publish to HuggingFace
        run: |
          hf repos delete Bingsu/bpsr-data --type space --missing-ok -y
          hf repos create Bingsu/bpsr-data --type space --sdk static
          hf upload Bingsu/bpsr-data ./dist / --repo-type space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
